---
- name: Call API and store results in facts
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display provisioning message
      debug:
        msg: "VM Provisioning status : IP: {{ assigned_hostname }} / Hostname: ({{ assigned_ip }}) / Deployed: {{ is_deployed }}..."

    - name: Set deploy fact for workflow
      set_stats:
        data:
          is_deployed: true
