- hosts: localhost
  gather_facts: false
  roles:
  - deploy-VM

# - hosts: deployed_vm
#   become: true
#   gather_facts: false
#   vars:
#     ansible_ssh_private_key_file: "{{ post_prov.key_file }}"
#     ansible_ssh_user: "cloud-user"
#   roles:
#   - post-prov