- hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove VM
      kubernetes.core.k8s:
        state: absent
        namespace: "{{ rhov.namespace }}"
        kind: VirtualMachine
        api_version: kubevirt.io/v1
        name: "{{ vm.name }}"
      register: result_remove_vm

    - name: Update Host status to provisioning
      uri:
        url: "{{ host_api_endpoint }}/{{ host_id }}/status"
        method: PUT
        headers:
          Content-Type: "application/json"
        body:
          status: "free"
        body_format: json
        return_content: yes
        status_code: 200
        validate_certs: no
      register: result_update_status

    - name: force fail since the VM is not deployed
      ansible.builtin.fail:
        msg: "Provsioning {{ vm.name }} in namespace {{ rhov.namespace }} has failed"
      

