---
 
- name: Include vars of users.yaml
  ansible.builtin.include_vars:
    file: group_vars/users.yaml

- name: Fail if openshift is in project name
  ansible.builtin.fail:
    msg: "DO NOT USE openshift in project name"
  when: "'openshift' in rhov.namespace"
  delegate_to: localhost

- name: "Create VirtualMachine"
  kubernetes.core.k8s:
    state: present
    template: vm.yml.j2
  delegate_to: localhost

- name: "Add VM to an inventory group"
  add_host:
    hostname: '{{ vm.ip }}'
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    inventory_dir: "inventory"
    groups: deployed_vm

