- name: Call the API and get JSON response
  uri:
    url: "{{ api_endpoint }}/{{ host_id }}"
    method: GET
    return_content: yes
    status_code: 200
    validate_certs: no
  register: api_response

- name: Set hostname and ip facts from API response
  set_fact:
    hostname: "{{ (api_response.json).data.hostname }}"
    ip: "{{ (api_response.json).data.ip }}"
    status: "{{ (api_response.json).data.status }}"

- name: Display hostname and ip facts
  debug:
    msg:
      - "Hostname: {{ hostname }}"
      - "IP: {{ ip }}"
      - "Status: {{ status }}"

- name: Set info fact for workflow
  set_stats:
    data:
      assigned_ip: "{{ ip }}"
      assigned_hostname: "{{ hostname }}"
      assigned_status: "{{ status }}"